import { baseIconsUrl } from "../constants";
import type { Protocol } from "./types";
/*
{
  id: string;
  name: string;
  address: string;
  symbol: string;
  url: string;
  description: string;
  chain: string;
  logo: null | string;
  audits: null | "0" | "1" | "2" | "3";
  gecko_id: string;
  cmcId: string;
  category: string;
  chains: string[];
  oracles: string[];
  forkedFrom: string[];
  module: string;
  twitter: string;
  language?: string;
  treasury?: string;
  tokensExcludedFromParent: {
      Avalanche: ["GPC"],    // ADD ALL TIME WITH BIG LETTER, NOT SMALL LETTER
    },
  excludeTvlFromParent?: boolean;
},
*/
/* Audits: Please follow this legend
0 -> No audits
1 -> Part of this protocol may be unaudited
2 -> Yes
3 -> This protocol is a fork of an existing audited protocol
*/
/*
`chain` is the first chain of a protocol we tracked at defillama,
  so if a protocol launches on Ethereum and we start tracking it there, and then it launches on polygon and
  we start tracking it on both polygon and ethereum, then `chain` should be set to `Ethereum`.
`chains` is not used by the current code, but good to fill it out because it is used in our test to detect errors
*/
const data6: Protocol[] = [
  {
    id: "7709",
    name: "MOKEE",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.mokee.app/
    description:
      "MOKEE Protocol is the first non-custodial crypto fail-safe protocol. Users deposit native tokens into personal vaults, designate heirs, and set an inactivity threshold",
    chain: "Binance",
    logo: `${baseIconsUrl}/mokee.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Token Locker",
    chains: ["Binance", "Base","Ethereum", "Polygon", "Arbitrum", "Optimism"],
    module: "mokee/index.js",
    twitter: "MokeeApp",
    audit_links: [],
    listedAt: 1776463251
  },
  {
    id: "7710",
    name: "Trinity Protocol",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://graceful-begonia-2b7634.netlify.app/.
    description:
      "Gold-collateralized USDC lending market on Morpho Blue (Arbitrum One)",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/trinity-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Arbitrum"],
    module: "trinity-protocol/index.js",
    twitter: "cameron_arc_ai",
    audit_links: [],
    listedAt: 1776465699
  },
  {
    id: "7711",
    name: "Liquid Protocol",
    address: null,
    symbol: "-",
    url: "https://app.liquidprotocol.org/tokens",
    description:
      "Liquid Protocol deploys ERC-20 tokens on Base with Uniswap V4 pools, locked liquidity, and configurable fee distribution",
    chain: "Base",
    logo: `${baseIconsUrl}/liquid-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "LIQUIDPROTOCOL",
    github: ["Liquid-Protocol-Ops"],
    dimensions: {
      fees: "liquid-protocol",
    },
  },
  {
    id: "7712",
    name: "Rainbow Token Launchpad",
    address: null,
    symbol: "-",
    url: "https://rainbow.me/",
    description:
      "A launchpad platform built by Rainbow team",
    chain: "Base",
    logo: `${baseIconsUrl}/rainbow-token-launchpad.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "rainbowdotme",
    parentProtocol: "parent#rainbow",
    dimensions: {
      fees: "rainbow-token-launchpad",
    },
  },
  {
    id: "7713",
    name: "GrelfSwap",
    address: "hedera:0.0.1159074",
    symbol: "GRELF",
    url: "https://grelfswap.com",
    description: "GrelfSwap is a DEX aggregator on Hedera",
    chain: "Hedera",
    logo: `${baseIconsUrl}/grelfswap.png`,
    audits: "0",
    gecko_id: "grelf",
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Hedera"],
    module: "dummy.js",
    twitter: "GRELF_",
    dimensions: {
      aggregators: "grelfswap",
      fees: "grelfswap",
    },
  },
  {
    id: "7714",
    name: "Circle CCTP",
    address: null,
    symbol: "-",
    url: "https://www.circle.com/cross-chain-transfer-protocol",
    description: "Circle helps businesses and developers harness the power of USDC for payments and commerce",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/circle-cctp.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum", "Base", "Polygon", "Optimism", "Arbitrum", "Avalanche", "Monad", "Unichain", "Linea", "Plume Mainnet", "Sonic", "World Chain", "XDC", "Hyperliquid L1", "Ink"],
    module: "dummy.js",
    twitter: "circle",
    stablecoins: ["usd-coin"],
    parentProtocol: "parent#circle",
    dimensions: {
      fees: "cctp"
    }
  },
  {
    id: "7715",
    name: "Paxos Stablecoin Issuer",
    address: null,
    symbol: "-",
    url: "https://paxos.com/",
    description:
      "Paxos is a financial technology company that provides stablecoin services to businesses and developers",
    chain: "Off Chain",
    logo: `${baseIconsUrl}/paxos-stablecoin-issuer.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Stablecoin Issuer",
    chains: ["Off Chain"],
    module: "dummy.js",
    twitter: "Paxos",
    parentProtocol: "parent#paxos",
    dimensions: {
      fees: "paxos"
    }
  },
  {
    id: "7716",
    name: "Lucky38",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://randomy.fun/
    description:
      "On-chain games for Openclaw on Base",
    chain: "Base",
    logo: `${baseIconsUrl}/lucky38.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["Base"],
    module: "lucky38/index.js",
    twitter: null,
    listedAt: 1776628155
  },
  {
    id: "7717",
    name: "ENNI",
    address: "0xE364450b3F702d12b02F0290E0392f02DE53b8E2",
    symbol: "ENNI",
    url: " ", // pending to add url https://enni.ch
    description:
      "Immutable CDP protocol on Ethereum. Borrow stablecoins against WETH at 0% interest. No governance. No admin keys",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/enni.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Ethereum"],
    module: "enni/index.js",
    oraclesBreakdown: [ 
      { name: "Chainlink", type: "Primary", proof: ["https://enni.ch/docs/security/oracles"] },
      { name: "RedStone", type: "Fallback", proof: ["https://enni.ch/docs/security/oracles"] } 
    ],
    twitter: "Enni_Index",
    audit_links: ["https://enni.ch/Hashlock-Audit.pdf", "https://enni.ch/Blockbite-Audit.pdf"],
    github: ["enni-ch"],
    listedAt: 1776628713,
  },
  {
    id: "7718",
    name: "SuiDex",
    address: null,
    symbol: "-",
    url: "https://dex.suidex.org/",
    description:
      "SuiDex is a Uniswap V2-style AMM DEX on Sui with 54 active trading pairs, yield farming (SuiFarm), and a VICTORY token locker",
    chain: "Sui",
    logo: `${baseIconsUrl}/suidex.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Sui"],
    module: "suidex/index.js",
    twitter: "suidexHQ",
    audit_links: ["https://suidex.gitbook.io/suidex/information/audits"],
    listedAt: 1776658891,
  },
  {
    id: "7719",
    name: "Durianfun",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://durianfun.xyz/
    description:
      "Fair-launch meme-token launchpad on KUB. Tokens start on an exponential bonding curve, then graduate to a sealed DurianAMM liquidity pool. No presale, no team allocation, 14.3% of trading fees shared back to creators",
    chain: "Bitkub",
    logo: `${baseIconsUrl}/durianfun.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Bitkub"],
    module: "durianfun/index.js",
    twitter: "duriandotfun",
    audit_links: ["https://durianandfun.gitbook.io/durianfun/overall-audits"],
    github: ["Duriandotfun"],
    listedAt: 1776659179,
  },
  {
    id: "7720",
    name: "Milk Finance",
    address: null,
    symbol: "-",
    url: "https://app.basedmilk.com",
    description:
      "Milk Finance is a USDC-backed stablecoin lending protocol on Base",
    chain: "Base",
    logo: `${baseIconsUrl}/milk-finance.jpg`,
    audits: "3",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Base"],
    module: "milk-finance/index.js",
    twitter: "gotBasedMilk",
    listedAt: 1776659651,
  },
  {
    id: "7721",
    name: "SoulBound Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://soulbound.finance
    description:
      "SoulBound Finance is a privacy-focused transfer protocol on Arbitrum that enables encrypted, wallet-to-wallet payments using one-time redeemable codes. It supports assets like ETH and stablecoins, with batched redemptions and a design that prevents linking senders to recipients",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/soulbound-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Arbitrum"],
    module: "soulbound-finance/index.js",
    twitter: "SoulboundSec",
    github: ["SoulboundSecurity"],
    listedAt: 1776740719,
  },
  {
    id: "7722",
    name: "Pyron",
    address: null,
    symbol: "-",
    url: "https://pyron.fi/",
    description:
      "Asset productivity layer of Fogo. Lend and Borrow without the wait, noise, or limits",
    chain: "Fogo",
    logo: `${baseIconsUrl}/pyron.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Fogo"],
    module: "pyron/index.js",
    twitter: "Pyronfi",
    github: ["pyron-finance"],
    audit_links: ["https://github.com/zenith-security/reports/blob/main/reports/Pyron%20Lendr%20-%20Zenith%20Audit%20Report.pdf"],
    listedAt: 1776741147,
  },
  {
    id: "7723",
    name: "PMI Protocol",
    address: "polygon:0x9DD6641423200b1FBd0BFF45f376BEE66Be1F4E4",
    symbol: "PMI",
    url: " ", // pending to add url https://pmiprotocol.xyz
    description:
      "On-chain index fund for prediction market infrastructure tokens. Deposit USDC, receive PMI shares at NAV. Vault holds UMA, WMATIC, and GNO via Uniswap V3",
    chain: "Polygon",
    logo: `${baseIconsUrl}/pmi-protocol.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Polygon"],
    module: "pmi-protocol/index.js",
    twitter: "predictionidx",
    github: ["ninjacornix"],
    listedAt: 1776741431,
  },
  {
    id: "7724",
    name: "Vaultfire",
    address: null,
    symbol: "-",
    url: " ", // pending to add url project didn't submit url
    description:
      "Vaultfire is an AI agent trust infrastructure protocol",
    chain: "Base",
    logo: `${baseIconsUrl}/vaultfire.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "AI Agents",
    chains: ["Base", "Avalanche", "Arbitrum", "Polygon"],
    module: "vaultfire/index.js",
    twitter: null,
    listedAt: 1776741959,
  },
  {
    id: "7725",
    name: "TopStrike",
    address: null,
    symbol: "-",
    url: "https://topstrike.io",
    description:
      "Real-time, one-tap Football trading game powered by MegaETH",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/topstrike.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gaming",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "TopStrikeIO",
    dimensions: {
      dexs: "topstrike",
      fees: "topstrike",
    },
  },
  {
    id: "7726",
    name: "ASPE Labs",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://aspelabs.xyz
    description:
      "Automated yield vault on HyperEVM. ERC4626-compliant; deposits USDC, trades on HyperCore via an agent wallet, and returns profits through share price appreciation",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/aspe-labs.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Hyperliquid L1"],
    module: "aspe-labs/index.js",
    twitter: "AspeLabs",
    github: ["aspe-labs"],
    listedAt: 1776742731,
  },
  {
    id: "7727",
    name: "Hubra",
    address: null,
    symbol: "-",
    url: "https://hubra.app/",
    description:
      "Hubra is a Solana-based DeFi protocol providing institutional-grade, non-custodial yield products, including liquid staking (raSOL) and automated yield vaults (raUSDC, raUSDT, raUSDS, raUSDG, raUSD1). It is designed to make professional yield strategies accessible to everyone",
    chain: "Solana",
    logo: `${baseIconsUrl}/hubra.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Solana"],
    module: "hubra/index.js",
    twitter: "HubraApp",
    github: ["Hubra-labs"],
    listedAt: 1776742981,
  },
  {
    id: "7728",
    name: "Apiary",
    address: "berachain:0x5e4d5f1E7b69Cdcd3faDb0cf182ea7821070Cbb5",
    symbol: "APIARY",
    url: "https://www.apiary.fi/",
    description:
      "Treasury-backed protocol designed to perpetually accumulate $BGT (Berachain Governance Token) through Berachain's Proof of Liquidity (PoL)",
    chain: "Berachain",
    logo: `${baseIconsUrl}/apiary.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Reserve Currency",
    chains: ["Berachain"],
    module: "apiary/index.js",
    twitter: "ApiaryFi",
    listedAt: 1776798425,
  },
  {
    id: "7729",
    name: "Dumpfun Gamified Launcher",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dumpfun.io
    description:
      "Dumpfun Gamified Launcher is a gamified token launchpad on Solana. Anyone can launch a mining token; users deploy SOL to a 5x5 grid per round, and VRF-picked winning squares split a SOL + token reward pool. Per reset: 87% winners, 1% creator, 10% buy-and-burn, 0.5% platform fee, 1.4% per-token motherlode, 0.1% global motherlode",
    chain: "Solana",
    logo: `${baseIconsUrl}/dumpfun-gamified-launcher.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Gamified Mining",
    chains: ["Solana"],
    module: "dumpfun-gamified-launcher/index.js",
    twitter: "dumpfundotio",
    audit_links: ["https://skynet.certik.com/projects/dumpfun"],
    treasury: "dumpfun-gamified-launcher.js",
    listedAt: 1776798678,
  },
  {
    id: "7730",
    name: "TxFlow Bridge",
    address: null,
    symbol: "-",
    url: "https://txflow.com/",
    description:
      "TxFlow is an open Layer 1 with multi-application ecosystem around TIP Liquidity Standards — where every Channel shares on-chain liquidity, settlement, and market data without bridging",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/txflow-bridge.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Arbitrum"],
    module: "txflow/index.js",
    twitter: "TxFlow_L1",
    parentProtocol: "parent#txflow",
    listedAt: 1776799092,
  },
  {
    id: "7731",
    name: "Sail.Money",
    address: null,
    symbol: "-",
    url: "https://sail.money/",
    description:
      "Sail is a non-custodial personal AI agent that manages stablecoins across DeFi protocols and networks, automatically reallocating capital to optimize risk-adjusted yield while helping protect capital with continuous risk monitoring and user-controlled permissions",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/sail.money.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum", "Base", "Arbitrum"],
    module: "sail/index.js",
    twitter: "SaildotMoney",
    listedAt: 1776799163,
  },
  {
    id: "7732",
    name: "Hit One",
    address: null,
    symbol: "-",
    url: "https://app.hit.one/r/5YPD66",
    referralUrl: "https://app.hit.one/r/5YPD66",
    description:
      "Hit One is a perpetual futures trading platform on MegaETH. Trades are aggregated off-chain at the venue layer (similar to Hyperliquid's model), so per-trade data is served from a public stats endpoint rather than indexed from on-chain events",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/hit-one.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "hitdotone",
    dimensions: {
      derivatives: "hitone",
      fees: "hitone",
    },
  },
  {
    id: "7733",
    name: "TxFlow Perps",
    address: null,
    symbol: "-",
    url: "https://app.txflow.com/",
    description:
      "TxFlow perpetuals are derivative products with no expiration date. They maintain price convergence with the underlying spot asset through funding payments rather than settlement dates",
    chain: "TxFlow",
    logo: `${baseIconsUrl}/txflow-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["TxFlow"],
    module: "dummy.js",
    twitter: "TxFlow_L1",
    parentProtocol: "parent#txflow",
    dimensions: {
      derivatives: "txflow-perps",
      fees: "txflow-perps",
      "open-interest": "txflow-perps-oi",
    },
  },
  {
    id: "7734",
    name: "Ledgity Yield",
    address: "0x482dF7483a52496F4C65AB499966dfcdf4DDFDbc",
    symbol: "LDY",
    url: "https://ledgity.finance/",
    description:
      "Real-world yield protocol offering USDC and EURC vaults backed by institutional fixed-income strategies",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/ledgity-yield.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum", "Sonic", "Arbitrum", "Base"],
    module: "ledgity/index.js",
    twitter: "LedgityYield",
    github: ["LedgityLabs"],
    listedAt: 1776808973,
  },
  {
    id: "7735",
    name: "Premarket",
    address: null,
    symbol: "-",
    url: "https://premarket.xyz/",
    description:
      "Premarket is a prediction-market style protocol for trading premarket/outcome exposure",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/premarket.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["MegaETH"],
    module: "premarket/index.js",
    twitter: "premarket_xyz",
    listedAt: 1776809132,
  },
  {
    id: "7736",
    name: "Chisino",
    address: null,
    symbol: "-",
    url: " ", // pending to add url chisino.io
    description:
      "Chisino is an instant payout game protocol on MegaETH. Its pioneer game is no-loss scratch cards. Scratch for instant prizes up to $10,000. 55% of cards pay out across 16 prize tiers. Every card you play, win or lose, generates a recovery ticket that works to return what you spent. No permanent loss. The protocol is built on Klarhaus, a prize-linked savings engine that splits each play between instant prizes, entry recovery, and protocol rewards. Deposits are backed 1:1 by stablecoins. All outcomes are determined by onchain VRF. Earn rewards every time you play",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/chisino.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["MegaETH"],
    module: "chisino/index.js",
    twitter: "trychisino",
    listedAt: 1776809625,
  },
  {
    id: "7737",
    name: "RISE Bridge",
    address: null,
    symbol: "-",
    url: "https://risechain.com/",
    description:
      "RISE is an Ethereum Layer 2 blockchain delivering near-instant transactions at unprecedented scale with sub-3ms latency and 100,000+ TPS capacity, all secured by Ethereum",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rise-bridge.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum"],
    module: "rise/index.js",
    twitter: "risechain",
    listedAt: 1776809759,
  },
  {
    id: "7738",
    name: "DumpFlow",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dumpfun.io
    description:
      "DumpFlow is Dumpfun's bonding-curve token launchpad on Solana. Anyone can mint a meme token with a configurable virtual SOL reserve, sell-lock period, and dynamic ramping limits. Buys/sells route SOL through a per-token liquidity pool; a 1% SOL fee accrues to the platform fee wallet and sell-side fees split 2.5%/2.5% to creator/company",
    chain: "Solana",
    logo: `${baseIconsUrl}/dumpflow.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "dumpflow/index.js",
    twitter: "dumpfundotio",
    audit_links: ["https://skynet.certik.com/projects/dumpfun"],
    listedAt: 1776810088,
  },
  // { // ownership was transffered to Uniswap: https://github.com/DefiLlama/DefiLlama-Adapters/pull/18866
  //   id: "7739",
  //   name: "Oku Trade",
  //   address: null,
  //   symbol: "-",
  //   url: "https://oku.trade/",
  //   description: "Oku Trade is a premium DEX interface offering advanced trading, deep liquidity, and superior analytics on the chain",
  //   chain: "0G",
  //   logo: `${baseIconsUrl}/oku-trade.jpg`,
  //   audits: "0",
  //   gecko_id: null,
  //   cmcId: null,
  //   tags: ["CLMM"],
  //   chains: ["0G"],
  //   module: "oku-trade/index.js",
  //   twitter: "okutrade",
  //   listedAt: 1776810414,
  // },
  {
    id: "7740",
    name: "Arche",
    address: null,
    symbol: "-",
    url: "https://arche.money",
    description: "Yield-bearing stablecoin vault aggregating best-in-class DeFi yields",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/arche.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Ethereum"],
    module: "arche-money/index.js",
    twitter: "yieldarche",
    audit_links: [
      "https://github.com/Kann-Audits/Kann-Audits/blob/main/reports/pdf-format/Arche-security-review-2026-05-03.pdf",
    ],
    listedAt: 1776810661,
  },
  {
    id: "7741",
    name: "RamsesX Polygon CL",
    address: "polygon:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a concentrated liquidity layer and exchange on Polygon, powered by x(3,3).",
    chain: "Polygon",
    logo: `${baseIconsUrl}/ramsesx-polygon-cl.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Polygon"],
    module: "ramsesx-poly-cl/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    audit_links: ["https://docs.ramses.xyz/pages/audits"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881424,
    dimensions: {
      fees: "ramsesx-poly-cl",
      dexs: "ramsesx-poly-cl",
    },
  },
  {
    id: "7742",
    name: "RamsesX Polygon Legacy",
    address: "polygon:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a ve(3,3) exchange on Polygon with legacy liquidity pools and x(3,3) governance.",
    chain: "Polygon",
    logo: `${baseIconsUrl}/ramsesx-polygon-legacy.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["ve(3,3)"],
    chains: ["Polygon"],
    module: "ramsesx-poly-legacy/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881440,
    dimensions: {
      fees: "ramsesx-poly-legacy",
      dexs: "ramsesx-poly-legacy",
    },
  },
  {
    id: "7743",
    name: "RamsesX Arbitrum CL",
    address: "arbitrum:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a concentrated liquidity layer and exchange on Arbitrum, powered by x(3,3).",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/ramsesx-arbitrum-cl.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Arbitrum"],
    module: "ramsesx-arb-cl/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    audit_links: ["https://docs.ramses.xyz/pages/audits"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881448,
    dimensions: {
      fees: "ramsesx-arb-cl",
      dexs: "ramsesx-arb-cl",
    },
  },
  {
    id: "7744",
    name: "RamsesX Arbitrum Legacy",
    address: "arbitrum:0x555570a286F15EbDFE42B66eDE2f724Aa1AB5555",
    symbol: "RAM",
    url: "https://ramses.xyz",
    description:
      "RamsesX is a ve(3,3) exchange on Arbitrum with legacy liquidity pools and x(3,3) governance.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/ramsesx-arbitrum-legacy.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["ve(3,3)"],
    chains: ["Arbitrum"],
    module: "ramsesx-arb-legacy/index.js",
    twitter: "RamsesExchange",
    forkedFromIds: ["2198", "1407"],
    parentProtocol: "parent#ramses-exchange-hl",
    listedAt: 1776881454,
    dimensions: {
      fees: "ramsesx-arb-legacy",
      dexs: "ramsesx-arb-legacy",
    },
  },
  {
    id: "7745",
    name: "YFarmer",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://yfarmer.xyz
    description:
      "YFarmer is a DeFi yield vault and risk curation protocol where users deposit USDC to access actively managed strategies.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/yfarmer.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Ethereum"],
    module: "yfarmer/index.js",
    twitter: null,
    listedAt: 1776882319,
  },
  {
    id: "7746",
    name: "Altera Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://altera.finance
    description:
      "Altera Vaults deploy capital into market-neutral, hedged, and structured-credit strategies operated by licensed fund managers.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/altera-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Ethereum"],
    module: "altera-finance/index.js",
    twitter: null,
    listedAt: 1776882684,
  },
  {
    id: "7747",
    name: "Streamlock",
    address: "solana:FNhcY1cwQvQqaM8CUjXSuoGKJniwC4maBRLqNRLipump",
    symbol: "LOCK",
    url: "https://www.streamlock.fun/",
    description:
      "Solana token launchpad with price-gated locks. Users buy launched memecoins via a bonding-curve AMM; purchases sit locked in on-chain escrows until each token hits its configured price milestones. Idle SOL reserves are staked as JitoSOL for yield that accrues to the protocol.",
    chain: "Solana",
    logo: `${baseIconsUrl}/streamlock.jpg`,
    audits: "0",
    gecko_id: "streamlock",
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "streamlock/index.js",
    twitter: "0xHao_",
    github: ["0xNike"],
    listedAt: 1776963621,
  },
  {
    id: "7748",
    name: "SpringX",
    address: null,
    symbol: "-",
    url: "https://springx.finance/",
    description:
      "SpringX is the gateway to the Plasma DeFi ecosystem facilitating yield generation through efficient auto-liquidity management.",
    chain: "Plasma",
    logo: `${baseIconsUrl}/springx.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Plasma"],
    module: "springx/index.js",
    twitter: "SpringX_Finance",
    audit_links: ["https://github.com/shieldify-security/audits-portfolio/blob/main/reports/SpringX-Security-Review.pdf"],
    listedAt: 1776964034,
  },
  {
    id: "7749",
    name: "Alchemix V3",
    address: "0xdBdb4d16EdA451D0503b854CF79D55697F90c8DF",
    symbol: "ALCX",
    url: "https://alchemix.fi/",
    description:
      "Alchemix is a DeFi protocol that allows for the creation of synthetic tokens that represent the future yield of a deposit. It enables users to retrieve near instant tokenized value against temporary* deposits of stablecoins.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/alchemix-v3.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Synthetics",
    chains: ["Ethereum", "Arbitrum", "Optimism"],
    module: "alchemix-v3/index.js",
    twitter: "AlchemixFi",
    audit_links: ["https://github.com/runtimeverification/publications/blob/main/reports/smart-contracts/Alchemix_v3.pdf"],
    parentProtocol: "parent#alchemix",
    listedAt: 1776975864,
  },
  {
    id: "7750",
    name: "Flying Tulip Lend",
    address: "0x5DD1A7A369e8273371d2DBf9d83356057088082c",
    symbol: "FT",
    url: "https://flyingtulip.com/lend/",
    description: "Flying Tulip Lend is a custom lending market on Sonic.",
    chain: "Sonic",
    logo: `${baseIconsUrl}/flying-tulip-lend.jpg`,
    audits: "2",
    gecko_id: "flying-tulip",
    cmcId: null,
    category: "Lending",
    chains: ["Sonic"],
    module: "dummy.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "flyingtulip_",
    listedAt: 1769459609,
    parentProtocol: "parent#flying-tulip",
    dimensions: {
      fees: "flying-tulip-lend"
    }
  },
  {
    id: "7751",
    name: "eva Markets",
    address: null,
    symbol: "-",
    url: "https://www.eva.markets",
    description: "eva Markets allows users to mint portable tokens backed by isolated credit.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/eva-markets.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Private Credit"],
    chains: ["Ethereum"],
    module: "eva/index.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "eva_markets",
    listedAt: 1777136758,
    dimensions: {
      fees: "eva"
    }
  },
  {
    id: "7752",
    name: "FrenFlow",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://frenflow.com
    description: "FrenFlow is the social + execution layer for prediction markets. A unified trading UI and Telegram bot with self-custody routing across Polymarket, Kalshi (via DFlow), and Predict.fun — plus native copytrading, social feed, and leaderboards.",
    chain: "Polygon",
    logo: `${baseIconsUrl}/frenflow.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Prediction Market",
    chains: ["Polygon"],
    module: "dummy.js",
    twitter: "frenflow",
    github: ["frenflow"],
    dimensions: {
      fees: "frenflow",
      dexs: "frenflow",
    }
  },
  {
    id: "7753",
    name: "Telegram Wallet",
    address: null,
    symbol: "-",
    url: "https://t.me/wallet",
    description: "Buy, sell and transfer crypto with zero fees on Telegram.",
    chain: "zkLighter",
    logo: `${baseIconsUrl}/telegram-wallet.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Interface",
    chains: ["zkLighter"],
    module: "dummy.js",
    twitter: "wallet_tg",
    dimensions: {
      fees: "telegram-wallet-perps",
    }
  },
  {
    id: "7754",
    name: "HypePool",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://hypepool.app
    description: "The first on-chain game protocol on HyperEVM. Multiple ways to play, with verifiable randomness via Chainlink VRF v2.5 routed through Base via CCIP.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/hypepool.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gaming",
    chains: ["Hyperliquid L1"],
    module: "hypepool/index.js",
    twitter: "HypePoolX",
    listedAt: 1777230068,
  },
  {
    id: "7755",
    name: "Kyan Blue Perps",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.kyan.blue/perps
    description: "Kyan Blue Perps is Kyan's perpetuals market.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/kyan-blue-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Arbitrum"],
    module: "kyan-blue/index.js",
    twitter: "KyanExchange",
    parentProtocol: "parent#premia",
    dimensions: {
      derivatives: "kyan",
      fees: "kyan",
      "active-users": "kyan",
    },
  },
  {
    id: "7756",
    name: "Kyan Blue Options",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.kyan.blue/
    description: "Kyan Blue Options is Kyan's options market.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/kyan-blue-options.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Options",
    chains: ["Arbitrum"],
    module: "dummy.js",
    twitter: "KyanExchange",
    parentProtocol: "parent#premia",
    dimensions: {
      options: "kyan",
    },
  },
  {
    id: "7757",
    name: "WeDeFin",
    address: null,
    symbol: "-",
    url: "https://app.wedefin.com/",
    description: "WeDeFin is a non-custodial index and portfolio app that lets users follow community-ranked crypto strategies, rebalance through DEXs, and route supported assets into Aave for yield.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/wedefin.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Indexes",
    chains: ["Ethereum", "Base", "Arbitrum"],
    module: "wedefin/index.js",
    twitter: "wedefin",
    audit_links: ["https://docs.wedefin.com/technical-overview/audits"],
    listedAt: 1777310614,
    dimensions: {
      fees: "wedefin",
    }
  },
  {
    id: "7758",
    name: "LayerZero V1",
    address: "ethereum:0x6985884c4392d348587b19cb9eaaf157f13271cd",
    symbol: "ZRO",
    url: "https://layerzero.network/",
    description:
      "LayerZero is a technology that enables applications to move data across blockchains, uniquely supporting censorship-resistant messages and permissionless development through immutable smart contracts.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/layerzero-v1.jpg`,
    gecko_id: null,
    cmcId: null,
    category: "Bridge",
    chains: ["Ethereum", "Binance", "Polygon", "Arbitrum", "Optimism", "Base", "Avalanche", "Harmony", "Fantom", "Linea", "Tron", "Scroll", "Mantle", "Blast", "Mode", "Aurora", "Celo", "Story", "Ink", 
      "Polygon zkEVM", "Sonic", "Berachain", "Unichain", "Movement", "Abstract", "MegaETH", "Sophon", "Morph", "Plasma", "Flare", "Monad"],
    module: "dummy.js",
    twitter: "LayerZero_Core",
    parentProtocol: "parent#layerzero",
    dimensions: {
      fees: "layerzerov1",
    }
  },
  {
    id: "7759",
    name: "Flying Tulip ftUSD",
    address: null,
    symbol: "-",
    url: "https://flyingtulip.com/",
    description: "ftUSD is a yield-bearing stablecoin backed by USDC, USDT and ftUSD-wrapped collateral deployed via MintAndRedeem into Aave yield strategies. Holders can stake into sftUSD to earn FT rewards funded by protocol fees that buy FT on the open market.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/flying-tulip-ftusd.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Ethereum", "Sonic"],
    module: "dummy.js",
    audit_links: ["https://docs.flyingtulip.com/risks/"],
    twitter: "flyingtulip_",
    listedAt: 1777298400,
    parentProtocol: "parent#flying-tulip",
    dimensions: {
      fees: "flying-tulip-ftusd"
    }
  },
  {
    id: "7760",
    name: "Veax Perps",
    address: null,
    symbol: "VEAX",
    url: "https://veax.com/",
    description:
      "Veax is an advanced DEX and PerpDEX built on Near Protocol and Orderly . Bringing together the best features of TradFi and DeFi for an unparalleled swap and trading experience.",
    chain: "Orderly",
    logo: `${baseIconsUrl}/veax-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Orderly Builder"],
    chains: ["Orderly"],
    module: "dummy.js",
    twitter: "veaxlabs",
    parentProtocol: "parent#veax",
    dimensions: {
      fees: "veax-perp",
      derivatives: "veax-perp"
    }
  },
  {
    id: "7761",
    name: "Bullet Perps",
    address: null,
    symbol: "-",
    url: "https://bullet.xyz/",
    description:
      "High-performance ZK rollup perpetuals and spot DEX settling on Solana.",
    chain: "Solana",
    logo: `${baseIconsUrl}/bullet-perps.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "Bulletxyz",
    audit_links: ["https://docs.bullet.xyz/bullet-network/audits"],
    oraclesBreakdown: [{name: "Pyth", type: "Primary", proof: ["https://docs.bullet.xyz/bullet-network/architecture/oracle"]}],
    parentProtocol: "parent#bullet",
    dimensions: {
      derivatives: "bullet-perp",
      "open-interest": "bullet"
    }
  },
  {
    id: "7762",
    name: "ShapeSwap V2",
    address: null,
    symbol: "-",
    url: "https://shapeswap.xyz/",
    description:
      "Concentrated-liquidity DEX on Shape chain. Uniswap V3 fork with a companion V2/AMM deployment.",
    chain: "Shape",
    logo: `${baseIconsUrl}/shapeswap-v2.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Shape"],
    forkedFromIds: ["2197"],
    module: "shapeswap-v2/index.js",
    twitter: "shape",
    parentProtocol: "parent#shapeswap",
    listedAt: 1777404083,
    dimensions: {
      dexs: "shapeswap-v2",
      fees: "shapeswap-v2",
    }
  },
  {
    id: "7763",
    name: "ShapeSwap V3",
    address: null,
    symbol: "-",
    url: "https://shapeswap.xyz/",
    description:
      "Concentrated-liquidity DEX on Shape chain. Uniswap V3 fork with a companion V2/AMM deployment.",
    chain: "Shape",
    logo: `${baseIconsUrl}/shapeswap-v3.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Shape"],
    forkedFromIds: ["2198"],
    module: "shapeswap-v3/index.js",
    twitter: "shape",
    parentProtocol: "parent#shapeswap",
    listedAt: 1777404089,
    dimensions: {
      dexs: "shapeswap-v3",
      fees: "shapeswap-v3",
    }
  },
  {
    id: "7764",
    name: "RSwap",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dex.reddicks.meme
    description:
      "RSwap is a meme-driven DEX built for the DCKS ecosystem. Designed as the core trading layer of DCKS, RSwap combines efficient pricing with high-energy community participation, making it both a functional DEX and a growth engine for the ecosystem.",
    chain: "Radix",
    logo: `${baseIconsUrl}/rswap.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Radix"],
    module: "rswap/index.js",
    twitter: "REDDICKS_XRD",
    audit_links: ["https://github.com/pessimistic-io/audits/blob/b886ee548241bc8066843ab110287058ff33ba4f/DefiPlaza%20Radix%20Security%20Analysis%20by%20Pessimistic.pdf"],
    listedAt: 1777404095,
  },
  {
    id: "7765",
    name: "Spreads Finance Leverage",
    address: null,
    symbol: "-",
    url: "https://spreads.fi/",
    description:
      "Spreads Finance has a suite of DeFi products starting with a yield and points vault for users to passively earn yield via market neutral derivative strategies or points from tokenless DeFi markets, all via a vault.",
    chain: "Ink",
    logo: `${baseIconsUrl}/spreads-finance-leverage.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    chains: ["Ink"],
    module: "spreads-strc-leverage/index.js",
    twitter: "spreads_fi",
    parentProtocol: "parent#spreads-finance",
    listedAt: 1777478521
  },
  {
    id: "7766",
    name: "R25",
    address: null,
    symbol: "-",
    url: "https://www.r25.xyz/",
    description:
      "R25 builds RWA vault infrastructure that enables automated and curated on-chain yield strategies",
    chain: "Pharos",
    logo: `${baseIconsUrl}/r25.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Money Market Funds"],
    chains: ["Pharos"],
    module: "r25/index.js",
    twitter: "R25Official",
    listedAt: 1777489095
  },
  {
    id: "7767",
    name: "x402",
    address: null,
    symbol: "-",
    url: "https://www.x402.org/",
    description:
      "x402 is an open payments standard that lets services charge for API and content access directly over HTTP, with payments settled through crypto-native rails",
    chain: "Base",
    logo: `${baseIconsUrl}/x402.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Payments",
    chains: ["Base","Arbitrum","Optimism","Polygon","Celo", "Hyperliquid L1","Binance","Avalanche","Abstract"],
    module: "dummy.js",
    twitter: null,
    dimensions: {
      dexs: "x402",
    }
  },
  {
    id: "7768",
    name: "Terminal",
    address: "solana:pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn",
    symbol: "PUMP",
    url: "https://terminal.pump.fun/",
    description: "Terminal is Pump.fun's advanced memecoin trading terminal",
    chain: "Solana",
    logo: `${baseIconsUrl}/terminal.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Telegram Bot",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "Pumpfun",
    parentProtocol: "parent#pump",
    dimensions: {
      fees: "trading-terminal"
    }
  },
  {
    id: "7769",
    name: "Trust Wallet Perps",
    address: "bsc:0x4b0f1812e5df2a09796481ff14017e6005508003",
    symbol: "TWT",
    url: "https://trustwallet.com/download",
    description: "Trust Wallet Perps is Trust Wallet's Perps platform",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/trust-wallet-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Hyperliquid Builder"],
    chains: ["Hyperliquid L1"],
    module: "dummy.js",
    twitter: "TrustWallet",
    parentProtocol: "parent#trust-wallet",
    dimensions: {
      fees: "trust-wallet-perps",
      derivatives: "trust-wallet-perps",
    }
  },
  {
    id: "7770",
    name: "NextRare",
    address: null,
    symbol: "-",
    url: "https://nextrare.cards/",
    description: "First perpetual TCG Gacha live on iOS and Android",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/nextrare.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Physical TCG",
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "NextRare_cards",
    dimensions: {
      fees: "nextrare",
      dexs: "nextrare",
    }
  },
  {
    id: "7771",
    name: "Pool Party",
    address: "base:0xEab49138BA2Ea6dd776220fE26b7b8E446638956",
    symbol: "SEND",
    url: "https://poolparty.fun",
    description: "First AMM on Canton Network. Built by Send Foundation. Accessible from the Send Canton Wallet. Launched February 2026",
    chain: "Canton",
    logo: `${baseIconsUrl}/pool-party.jpg`,
    audits: "0",
    gecko_id: "send-token-2",
    cmcId: "27376",
    tags: ["AMM"],
    chains: ["Canton"],
    module: "pool-party/index.js",
    twitter: "Send",
    listedAt: 1777517069,
    dimensions: {
      fees: "pool-party",
      dexs: "pool-party",
    }
  },
  {
    id: "7772",
    name: "Phlox",
    address: null,
    symbol: "-",
    url: "https://phlox.social",
    description: "Phlox is a LUKSO-focused DeFi app with a Uniswap V3-style DEX",
    chain: "LUKSO",
    logo: `${baseIconsUrl}/phlox.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    forkedFromIds: ["2198"],
    chains: ["LUKSO"],
    module: "phlox/index.js",
    twitter: "phloxsocial",
    github: ["phlox-labs"],
    listedAt: 1777517385
  },
  {
    id: "7773",
    name: "Bundie",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://bundie.fi
    description: "Bundie allows anyone to bundle DeFi yield strategies across multiple chains for AI agents and humans to invest in",
    chain: "Base",
    logo: `${baseIconsUrl}/bundie.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Base", "Scroll", "Arbitrum", "Avalanche", "Optimism"],
    module: "bundie/index.js",
    twitter: "BundieDefi",
    audit_links: ["https://sherlock-files.ams3.digitaloceanspaces.com/reports/2026.04.09%20-%20Final%20-%20Bundie%20Collaborative%20Audit%20Report%201775738963.pdf"],
    github: ["bundie-fi"],
    listedAt: 1777576628
  },
  // { only chain fees are tracked for Arweave, using normalizeChain.ts
  //   id: "7774",
  //   name: "Arweave",
  //   address: null,
  //   symbol: "AR",
  //   url: "https://arweave.org/",
  //   description: "Arweave is a decentralized permanent storage network that lets users pay once to store data onchain-like, with node incentives designed to keep the data available indefinitely",
  //   chain: "Arweave",
  //   logo: `${baseIconsUrl}/arweave.jpg`,
  //   audits: "0",
  //   gecko_id: "arweave",
  //   cmcId: "5632",
  //   category: "Chain",
  //   chains: ["Arweave"],
  //   module: "dummy.js",
  //   twitter: "ArweaveEco",
  //   dimensions: {
  //     fees: "arweave",
  //   }
  // },
  {
    id: "7775",
    name: "Ryoshi Royale",
    address: "cronos:0x055c517654d72A45B0d64Dc8733f8A38E27Fd49C",
    symbol: "RYOSHI",
    url: " ", // pending to add url https://ryoshiroyale.com/
    description: "Ryoshi Royale is an NFT-based battle arena platform built on the Cronos blockchain that transforms Ryoshi NFTs into playable heroes for competitive gaming. Players can customize their Ryoshi with equipment and training points in order to compete in strategic daily and weekly battles to earn cryptocurrency rewards",
    chain: "Cronos",
    logo: `${baseIconsUrl}/ryoshi-royale.jpg`,
    audits: "0",
    gecko_id: "ryoshi-with-knife",
    cmcId: null,
    category: "Gaming",
    chains: ["Cronos"],
    module: "ryoshi-royale/index.js",
    twitter: "ryoshiwithknife",
    listedAt: 1777600134
  },
  {
    id: "7776",
    name: "Nerona",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.nerona.xyz//
    description: "Nerona is a Fluent-based stablecoin app built around USDnr, a yield-bearing stablecoin that routes deposits into onchain yield and connects users to lending, card, and investment products",
    chain: "Fluent",
    logo: `${baseIconsUrl}/nerona.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Fluent","Ethereum"],
    module: "nerona-usd/index.js",
    twitter: "Neronaxyz",
    listedAt: 1777660684
  },
  {
    id: "7777",
    name: "Dango Perps",
    address: null,
    symbol: "-",
    url: "https://dango.exchange/",
    description:
      "Dango Perps is the perpetual trading platform that lets users trade on the Dango ecosystem",
    chain: "Dango",
    logo: `${baseIconsUrl}/dango-perps.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Dango"],
    module: "dummy.js",
    twitter: "dango",
    parentProtocol: "parent#dango",
    audit_links: ["https://dango-4.gitbook.io/dango-docs/audits"],
    dimensions: {
      derivatives: "dango",
      fees: "dango",
      "open-interest": "dango-oi",
    }
  },
  {
    id: "7778",
    name: "UpDown",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.updown.xyz
    description:
      "Updown is a decentralized perpetual exchange on Celo, offering deep liquidity and leveraged trading up to 100x",
    chain: "Celo",
    logo: `${baseIconsUrl}/updown.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Celo"],
    module: "updown/index.js",
    twitter: "updownxyz",
    audit_links: ["https://www.updown.xyz/#/auditReport"],
    forkedFromIds: ["3365"],
    listedAt: 1778005502,
    dimensions: {
      derivatives: "updown",
      fees: "updown",
    }
  },
  {
    id: "7779",
    name: "Tempo Fee AMM",
    address: null,
    symbol: "-",
    url: "https://tempo.xyz/",
    description:
      "Tempo Fee AMM is a decentralized exchange on Tempo.",
    chain: "Tempo",
    logo: `${baseIconsUrl}/tempo-fee-amm.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    chains: ["Tempo"],
    module: "tempo-fee-amm/index.js",
    twitter: "tempo",
    parentProtocol: "parent#tempo-dex",
    listedAt: 1777743055,
    dimensions: {
      fees: "tempo-fee-amm",
      dexs: "tempo-fee-amm",
    }
  },
  {
    id: "7780",
    name: "Dune Protocol",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.dune.supply/
    description:
      "DUNE is a competitive onchain mining protocol on Ethereum. Every 60 seconds, miners deploy ETH onto a 5×5 grid of 25 blocks. When the round ends, one block is selected at random onchain — miners on that block take home the pot while everyone else waits for the next round.",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/dune-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gamified Mining",
    chains: ["Arbitrum"],
    module: "dummy.js",
    twitter: "dunesupply",
    listedAt: 1777743571,
    dimensions: {
      fees: "dune-supply",
    }
  },
  {
    id: "7781",
    name: "Tsunami V3",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.nami.ink/swap
    description:
      "Concentrated liquidity DEX on Ink (Uniswap V3 fork). Standard 8-tier fee schedule and standard V3 pool math; no protocol-fee switch enabled.",
    chain: "Ink",
    logo: `${baseIconsUrl}/tsunami-v3.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Ink"],
    module: "tsunami-v3/index.js",
    forkedFromIds: ["2198"],
    twitter: null,
    dimensions: {
      fees: "tsunami",
      dexs: "tsunami",
    }
  },
  {
    id: "7782",
    name: "EasyA Kickstart",
    address: null,
    symbol: "-",
    url: "https://kickstart.easya.io/",
    description: "Permissionless ideas launchpad on Solana built on top of Meteora Dynamic Bonding Curve",
    chain: "Solana",
    logo: `${baseIconsUrl}/easya-kickstart.svg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "EasyA_Kickstart",
    listedAt: 1777673109,
    dimensions: {
      fees: "easya-kickstart",
    },
  },
  {
    id: "7783",
    name: "KrokoSwap V2",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://krokoswap.io/
    description: "Kroko is a decentralized exchange built on the Kasplex blockchain, supporting both V2 (constant product) and V3 (concentrated liquidity) protocols with a Universal Router for unified swap execution",
    chain: "Kasplex",
    logo: `${baseIconsUrl}/krokoswap-v2.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["AMM"],
    forkedFromIds: ["2197"],
    chains: ["Kasplex"],
    module: "krokoswap-v2/index.js",
    twitter: "Kroko_Swap",
    parentProtocol: "parent#krokoswap",
    listedAt: 1777849001,
  },
  {
    id: "7784",
    name: "KrokoSwap V3",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://krokoswap.io/
    description: "Kroko is a decentralized exchange built on the Kasplex blockchain, supporting both V2 (constant product) and V3 (concentrated liquidity) protocols with a Universal Router for unified swap execution",
    chain: "Kasplex",
    logo: `${baseIconsUrl}/krokoswap-v3.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    forkedFromIds: ["2198"],
    chains: ["Kasplex"],
    module: "krokoswap-v3/index.js",
    twitter: "Kroko_Swap",
    parentProtocol: "parent#krokoswap",
    listedAt: 1777849011,
  },
  {
    id: "7785",
    name: "K613",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://k613.net/
    description: "K613 is an over-collateralized lending protocol on Monad, forked from Aave V3.",
    chain: "Monad",
    logo: `${baseIconsUrl}/k613.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Lending",
    forkedFromIds: ["1599"],
    oraclesBreakdown: [{name: "Chainlink", type: "Primary", proof: ["https://github.com/DefiLlama/DefiLlama-Adapters/pull/19058"]}],
    chains: ["Monad"],
    module: "k613/index.js",
    twitter: "k613_official",
    github: ["K613-Official"],
    listedAt: 1777849497,
  },
  {
    id: "7786",
    name: "Cork Phoenix",
    address: null,
    symbol: "-",
    url: "https://app.cork.tech/",
    description: "Cork Phoenix is a programmable risk layer for onchain assets. Users deposit a Collateral Asset to mint cPT (principal token) and cST (swap token). cST holders can swap their Reference Asset for the Collateral Asset at any time before expiry — providing guaranteed redemption liquidity against depeg risk.",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/cork-phoenix.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Insurance",
    chains: ["Ethereum"],
    module: "cork-phoenix/index.js",
    twitter: "Corkprotocol",
    parentProtocol: "parent#cork-protocol",
    listedAt: 1777850067,
  },
  {
    id: "7787",
    name: "Tizi",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://tizi.money/
    description: "Tizi is a cross-chain yield aggregation protocol. Its main products are the asset-backed stablecoin TD and its staked counterpart stTD",
    chain: "Base",
    logo: `${baseIconsUrl}/tizi.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Base"],
    module: "tizi/index.js",
    twitter: "Tizi_Money",
    audit_links: ["https://2781107368-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FlxAaGBCj8m8RA8EcZ25F%2Fuploads%2FEJb3Xu5zhoktjv1DRmti%2FTizi%20audit%20by%20Beosin.pdf?alt=media&token=738f8007-4817-4b9d-9709-697fcc6bd6a4"],
    github: ["tizimoney"],
    listedAt: 1777850271,
  },
  {
    id: "7788",
    name: "XAUE Protocol",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://xaue.com/
    description: "XAUE is an institutional-grade decentralized asset enhancement protocol built on Ethereum. Serving as the Treasury Layer for Tether Gold (XAUt), it provides institutional holders of non-yielding assets (XAUt/Physical Gold) with a decentralized finance interest-bearing solution. XAUE aims to become a foundational anchor asset for gold and a so-called “qualified margin asset” in a decentralized finance environment",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/xaue-protocol.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Commodities"],
    chains: ["Ethereum"],
    module: "dummy.js",
    twitter: "Xaue_Protocol",
    dimensions: {
      fees: "xaue",
    },
  },
  {
    id: "7789",
    name: "Plasma One",
    address: null,
    symbol: "-",
    url: "https://www.plasma.to/one",
    description: "Plasma One is a next-generation card product built on the Plasma Chain, an EVM-compatible L1 optimised for stablecoin payments and everyday spending. It combines a yield-bearing Earn product (P1USD) with gasless Checkings accounts, giving users a seamless on-chain banking experience",
    chain: "Plasma",
    logo: `${baseIconsUrl}/plasma-one.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Crypto Card Issuer",
    chains: ["Plasma"],
    module: "plasma-one/index.js",
    twitter: "Plasma",
    dimensions: {
      fees: "plasma-one",
    },
  },
  {
    id: "7790",
    name: "HypeZion Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://www.hypezion.com/
    description: "Structured product protocol on Hyperliquid L1. Issues stablecoin (hzUSD) and leverage token (BullHYPE) backed by HYPE reserves",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/hypezion-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Hyperliquid L1"],
    module: "hypezion/index.js",
    twitter: "0xhypezion",
    listedAt: 1777915629,
  },
  {
    id: "7791",
    name: "Thaw",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://thaw.bet/
    description: "Provably fair on-chain casino on HyperEVM with 6 games powered by Pyth Entropy for verifiable randomness",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/thaw.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: "Luck Games",
    chains: ["Hyperliquid L1"],
    module: "thaw/index.js",
    twitter: "thawdotbet",
    audit_links: ["https://thaw.bet/peckshield-audit.pdf"],
    oraclesBreakdown: [{name: "Pyth", type: "RNG", proof: ["https://thaw.bet"]}],
    dimensions: {
      fees: "thaw",
      dexs: "thaw",
    },
    listedAt: 1777918603,
  },
  {
    id: "7792",
    name: "Backed AAO",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://backed.app
    description: "Backed lets users create and fund Autonomous Agent Organizations on MegaETH through on-chain raises and treasury-managed agent execution",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/backed-aao.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["MegaETH"],
    module: "backed-aao/index.js",
    twitter: "BackedApp",
    listedAt: 1777919202,
  },
  {
    id: "7793",
    name: "Zama",
    address: "0xa12cc123ba206d4031d1c7f6223d1c2ec249f4f3",
    symbol: "ZAMA",
    url: "https://www.zama.org/",
    description: "Zama is an open source cryptography company building state-of-the-art Fully Homomorphic Encryption (FHE) solutions for blockchain",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/zama.jpg`,
    audits: "0",
    gecko_id: "zama",
    cmcId: "39332",
    category: "Privacy",
    chains: ["Ethereum"],
    module: "zama/index.js",
    twitter: "zama",
    github: ["zama-ai"],
    listedAt: 1777919449,
  },
  {
    id: "7794",
    name: "Deluthium",
    address: null,
    symbol: "-",
    url: "https://deluthium.ai/",
    description: "Deluthium is an AI-native trading execution protocol that uses reinforcement learning to shard and route orders across liquidity sources while protecting user intent from public mempool exposure",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/deluthium.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Ethereum"],
    module: "dummy.js",
    twitter: "Deluthium",
    disabled: "project not live yet",
    dimensions: {
      fees: "deluthium",
      aggregators: "deluthium",
    },
  },
  {
    id: "7795",
    name: "Alvara",
    address: "0x8e729198d1c59b82bd6bba579310c40d740a11c2",
    symbol: "ALVA",
    url: "https://alvara.xyz",
    description: "Alvara is an on-chain basket/fund management protocol built around the ERC-7621 basket token standard",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/alvara.jpg`,
    audits: "0",
    gecko_id: "alvara-protocol",
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Ethereum"],
    module: "alvara/index.js",
    twitter: "AlvaraProtocol",
    github: ["Alvara-Protocol"],
    listedAt: 1778005731,
  },
  {
    id: "7796",
    name: "Unblock Equity",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.unblockequity.com/earn
    description: "Tokenized junior-lien home-equity loans. USDC lending on Base via 24 segmented MetaMorpho V2 vaults (verification × recovery × breathing-room escrow)",
    chain: "Base",
    logo: `${baseIconsUrl}/unblock-equity.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "RWA Lending",
    chains: ["Base"],
    module: "unblock-equity/index.js",
    twitter: "UnblockEquity",
    listedAt: 1778006088,
  },
  {
    id: "7797",
    name: "Sova",
    address: null,
    symbol: "-",
    url: "https://sova.io/",
    description: "Sova is a cross-chain Bitcoin liquidity protocol with a live Base ERC-4626 vault that accepts cbBTC and issues svBTC",
    chain: "Base",
    logo: `${baseIconsUrl}/sova.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Base"],
    module: "sova/index.js",
    twitter: "SovaBTC",
    github: ["SovaNetwork"],
    listedAt: 1778007011,
  },
  {
    id: "7798",
    name: "Cube",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://cubee.ee
    description: "Cube is a Solana DEX with weighted multi-token pools (up to 10 tokens) and virtual balances that let LPs concentrate liquidity within configurable price ranges. Swap fee and protocol fee share are configurable per pool",
    chain: "Solana",
    logo: `${baseIconsUrl}/cube.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["Weighted Pool AMM"],
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "cubee_ee",
    github: ["cubee-ee"],
    dimensions: {
      dexs: "cube",
    },
  },
  {
    id: "7799",
    name: "Jade",
    address: "solana:Cvx1KNrtcSu7nxC26gH2MNNLNXpEqAXni5YEuSStfJfh",
    symbol: "JADE",
    url: " ", // pending to add url https://jade.supply
    description: "Jade is a Solana-native, fair-launch store-of-value protocol with on-chain mining, forked from ORE",
    chain: "Solana",
    logo: `${baseIconsUrl}/jade.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gamified Mining",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "jadeprotocol",
    forkedFromIds: ["6893"],
    dimensions: {
      fees: "jade",
    },
  },
  {
    id: "7800",
    name: "Anthias Labs",
    address: null,
    symbol: "-",
    url: "https://anthias.xyz",
    description: "Anthias Labs is a boutique on-chain advisory firm focused on DeFi risk management and system design",
    chain: "Base",
    logo: `${baseIconsUrl}/anthias-labs.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Risk Curators",
    chains: ["Base"],
    module: "anthias/index.js",
    twitter: "anthiasxyz",
    github: ["anthias-labs"],
    listedAt: 1778007858,
  },
  {
    id: "7801",
    name: "GRIDer Perps",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://app.grider.xyz
    description: "Non-custodial grid trading on Hyperliquid via agent wallets. Users connect their wallet and run 24/7 grid strategies, with built-in backtesting and minimal fees.",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/grider-perps.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ['Hyperliquid Builder'],
    chains: ["Hyperliquid L1"],
    module: "dummy.js",
    twitter: "griderxyz",
    dimensions: {
      fees: "grider-perps",
      derivatives: "grider-perps",
    },
  },
  {
    id: "7802",
    name: "Monster",
    address: null,
    symbol: "-",
     url: "https://mnstr.xyz?ref=DARKRAIGUYARCANE",
    referralUrl: "https://mnstr.xyz?ref=DARKRAIGUYARCANE",
    description: "A physical trading card game on MegaETH",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/monster.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: 'Physical TCG',
    chains: ["MegaETH"],
    module: "dummy.js",
    twitter: "mnstr",
    dimensions: {
      fees: "monster",
      dexs: "monster",
    },
  },
  {
    id: "7803",
    name: "RERANGE",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://rerange.xyz
    description: "Liquid Orders Protocol",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/rerange.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: 'Derivatives',
    chains: ["Ethereum", "Base"],
    module: "dummy.js",
    twitter: "rerange_xyz",
    github: ["rerange-xyz"],
    dimensions: {
      fees: "rerange"
    },
  },
  {
    id: "7804",
    name: "Blackhaven",
    address: null,
    symbol: "RBT",
    url: " ", // pending to add url https://app.blackhaven.xyz/
    description: "Reserve-powered liquidity engine",
    chain: "MegaETH",
    logo: `${baseIconsUrl}/blackhaven.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: 'Reserve Currency',
    chains: ["MegaETH"],
    module: "blackhaven/index.js",
    treasury: "blackhaven.js",
    twitter: "blackhaven",
    audit_links: ["https://docs.blackhaven.xyz/resources/audit"],
    listedAt: 1778090442,
    warningBanners: [
      {
        message: "Blackhaven has some red flags and users have reported concerns. Be careful.",
        level: "alert",
      }],
  },
  {
    id: "7805",
    name: "Slender",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://slender.fi/
    description: "Slender is a noncustodial overcollateralized lending protocol on Soroban (Stellar).",
    chain: "Stellar",
    logo: `${baseIconsUrl}/slender.jpg`,
    audits: "2",
    gecko_id: null,
    cmcId: null,
    category: 'Lending',
    chains: ["Stellar"],
    module: "slender/index.js",
    twitter: "Slender_fi",
    audit_links: ["https://slender.fi/Slender_security_report_by_Certora.pdf"],
    listedAt: 1778094763,
  },
  {
    id: "7806",
    name: "RISEx",
    address: null,
    symbol: "-",
    url: "https://www.rise.trade/en",
    description: "RISEx is a fully onchain perpetuals exchange built on RISE Chain.",
    chain: "RISE",
    logo: `${baseIconsUrl}/risex.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: 'Derivatives',
    chains: ["RISE"],
    module: "risex/index.js",
    oraclesBreakdown: [{name: "Stork", type: "Primary", proof: ["https://docs.risechain.com/docs/risex/core/oracle#stork-oracle"]}],
    twitter: "risextrade",
    listedAt: 1778097214,
    dimensions: {
      "open-interest": "risex-perps-oi",
      derivatives: {
        adapter: "risex-perps",
        genuineSpikes: [["2026-05-07", "-"]]
      }
    },
  },
  {
    id: "7807",
    name: "Hermetica HBTC",
    address: null,
    symbol: "-",
    url: "https://hermetica.fi",
    description: "hBTC is Hermetica’s Bitcoin yield product",
    chain: "Stacks",
    logo: `${baseIconsUrl}/hermetica-hbtc.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: 'Anchor BTC',
    chains: ["Stacks"],
    module: "hermetica-hbtc/index.js",
    twitter: "HermeticaFi",
    parentProtocol: "parent#hermetica",
    excludeTvlFromParent: true, // full tvl value is represented under the usdh product
    listedAt: 1778142267
  },
  {
    id: "7808",
    name: "Monolith Market",
    address: null,
    symbol: "-",
    url: "https://monolith.market",
    description: "Monolith is a permissionless protocol for creating crypto-backed stablecoins built to last: choose the collateral, oracle, and parameters, then deploy your own crypto-backed stablecoin",
    chain: "Ethereum",
    logo: `${baseIconsUrl}/monolith-market.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "CDP",
    chains: ["Ethereum"],
    module: "monolith-market/index.js",
    twitter: "MonolithMarket",
    github: ["MonolithMarket"],
    listedAt: 1778171359
  },
  {
    id: "7809",
    name: "Reppo",
    address: "base:0xFf8104251E7761163faC3211eF5583FB3F8583d6",
    symbol: "REPPO",
    url: "https://reppo.xyz/",
    description: "Reppo enables AI agents, Physical AI and Humans to access high-quality verifiable training data on-demand",
    chain: "Base",
    logo: `${baseIconsUrl}/reppo.jpg`,
    audits: "0",
    gecko_id: "reppo",
    cmcId: "38996",
    category: "Prediction Market",
    chains: ["Base"],
    module: "reppo/index.js",
    twitter: "reppo",
    github: ["Reppo-Labs"],
    audit_links: ["https://github.com/Reppo-Labs/audit-reports"],
    listedAt: 1778176431
  },
  {
    id: "7810",
    name: "VisionBoard Vault",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://vault.visionboardfinance.com
    description: "VisionBoard Vault is a HyperEVM perps strategy vault where users deposit USDC for VBV shares, with capital traded algorithmically on Hyperliquid and vault returns reflected through NAV per share",
    chain: "Hyperliquid L1",
    logo: `${baseIconsUrl}/visionboard-vault.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Hyperliquid L1"],
    module: "visionboard-vault/index.js",
    twitter: null,
    listedAt: 1778176691
  },
  {
    id: "7811",
    name: "Defimarketplus",
    address: "arbitrum:0x09fd7e0d021D29106c534Edfb4Ea817AC0ea7F84",
    symbol: "DMTp",
    url: " ", // pending to add url https://dmtp.io
    description: "Non-custodial USD yield vault on Arbitrum. ERC-4626 vault routing USDC across whitelisted lending venues (Aave V3, with more under governance review). 0.15% deposit / 0.10% exit fees, no management or performance fee. Treasury yield routes 70% to vault PPS for depositors, 30% to DMTp buyback-and-burn via CoW Protocol",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/defimarketplus.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Arbitrum"],
    module: "defimarketplus/index.js",
    twitter: null,
    github: ["fxspeiser"],
    listedAt: 1778177389
  },
  {
    id: "7812",
    name: "Orai Quant Terminal",
    address: null,
    symbol: "-",
    url: "https://quant.orai.io/vault",
    description: "Quant is an Oraichain strategy vault product on Arbitrum that allocates deposited assets into ERC-4626 quant vaults",
    chain: "Arbitrum",
    logo: `${baseIconsUrl}/orai-quant-terminal.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Onchain Capital Allocator",
    chains: ["Arbitrum"],
    module: "orai-quant-terminal/index.js",
    twitter: "oraichain",
    listedAt: 1778177963
  },
  {
    id: "7813",
    name: "Xeno Money",
    address: null,
    symbol: "-",
    url: "https://app.xeno.money/",
    description: "Xeno Money's sISKe vault is a Base ERC-4626 yield vault where users deposit Monerium's ISKe stablecoin and receive sISKe, with yield passed through from the underlying reserves",
    chain: "Base",
    logo: `${baseIconsUrl}/xeno-money.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield",
    chains: ["Base"],
    module: "xeno-money/index.js",
    twitter: "Xeno_Money",
    listedAt: 1778189505
  },
  {
    id: "7814",
    name: "Land Bid",
    address: "base:0xB738b1568F08B0d6894a580Ef805E9298ebFaB46",
    symbol: "LAND",
    url: " ", // pending to add url https://landbid.xyz
    description: "Land Bid is a competitive on-chain continent mining game on Base where players pay ETH to conquer continents and earn LAND tokens through ongoing gameplay",
    chain: "Base",
    logo: `${baseIconsUrl}/land-bid.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Gamified Mining",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "landbidbase",
    github: ["landbidbase"],
    dimensions: {
      fees: "landbid",
      dexs: "landbid",
    }
  },
  {
    id: "7815",
    name: "Tigris Mezo V3",
    address: null,
    symbol: "-",
    url: "https://mezo.org/explore/pools",
    description: "A concentrated liquidity DEX based on Velodrome Slipstream",
    chain: "Mezo",
    logo: `${baseIconsUrl}/tigris-mezo-v3.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    tags: ["CLMM"],
    chains: ["Mezo"],
    module: "mezo-tigris-v3/index.js",
    forkedFromIds: ["2198"],
    twitter: "MezoNetwork",
    parentProtocol: "parent#mezo-swap",
    listedAt: 1778194227
  },
  {
    id: "7816",
    name: "Mezo Vaults",
    address: null,
    symbol: "-",
    url: "https://mezo.org/earn/vaults",
    description: "Mezo Vaults are yield-generating strategies that deploy your assets across DeFi to earn returns. Deposit into a vault, receive a receipt token representing your position, and let the strategist optimize for yield",
    chain: "Mezo",
    logo: `${baseIconsUrl}/mezo-vaults.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Yield Aggregator",
    chains: ["Mezo"],
    module: "mezo-vaults/index.js",
    twitter: "MezoNetwork",
    parentProtocol: "parent#mezo-swap", // pending to add parent protocol , added since was done
    listedAt: 1778194507
  },
  {
    id: "7817",
    name: "Rise.rich",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://rise.rich/
    description: "Solana launchpad with built-in lending. Token bonding curves and borrow markets are accounted for by the underlying Mayflower program",
    chain: "Solana",
    logo: `${baseIconsUrl}/rise.rich.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Launchpad",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "risedotrich",
    github: ["riserich"],
    listedAt: 1778254222,
    dimensions: {
      dexs: "rise-launchpad",
      fees: "rise-launchpad",
    },
  },
  {
    id: "7818",
    name: "Quai Network",
    address: null,
    symbol: "QUAI",
    url: "https://www.qu.ai/",
    description: "Quai is a Proof-of-Work Layer 1 that uses merged mining and parallel execution shards, with QUAI for EVM-compatible smart contract activity and QI as a UTXO-based payment token",
    chain: "Quai",
    logo: `${baseIconsUrl}/quai-network.jpg`,
    audits: "0",
    gecko_id: "quai-network",
    cmcId: "22354",
    category: "Chain",
    chains: ["Quai"],
    module: "dummy.js",
    twitter: "QuaiNetwork",
  },
  {
    id: "7819",
    name: "DEXR",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://dexr.finance
    description: "DEXR is a DEX aggregator on Base mainnet that routes swaps across 8 underlying DEXes to find the best execution price",
    chain: "Base",
    logo: `${baseIconsUrl}/dexr.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "DEX Aggregator",
    chains: ["Base"],
    module: "dummy.js",
    twitter: "DexrFinance",
    dimensions: {
      aggregators: "dexr",
      fees: "dexr",
    },
  },
  {
    id: "7820",
    name: "Sour Finance",
    address: null,
    symbol: "-",
    url: " ", // pending to add url https://sour.finance/
    description: "Sour is a Solana perpetuals DEX",
    chain: "Solana",
    logo: `${baseIconsUrl}/sour-finance.jpg`,
    audits: "0",
    gecko_id: null,
    cmcId: null,
    category: "Derivatives",
    chains: ["Solana"],
    module: "dummy.js",
    twitter: "SourFinance",
    dimensions: {
      derivatives: "sour",
      fees: "sour",
    },
  },
];
export default data6;
